### ISSUE TITLE
setup project

### ISSUE THREAD

**Issue by Ben-21** [Ben-21/capstone-neuefische#1]
# Acceptance criteria

- [ ] This is something that can be verified to show that this user story is satisfied.

# Tasks
- [ ] create project in IntelliJ
- [ ] create frontend
- [ ] create backend
- [ ] add / configure CI
- [ ] add / configure CD
- [ ] add / configure gitignore
- [ ] add / configure MongoDB
