### ISSUE TITLE
add classes and models

### ISSUE THREAD

**Issue by Ben-21** [Ben-21/capstone-neuefische#2]
# User story
As a ..., I want to ..., so I can ...

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria
- [ ] There is a class/ record in the backend and a model in the frontend.

# Tasks

## Frontend
- [ ] create model "Project", with:
  - id
  - name
  - description
  - category
  - demands
  - progress
  - location

- [ ] create enum "Category", with:
  - Donation
  - Participation

- [ ] create enum "Demand", with:
  - MoneyDonation
  - DonationInKind
  - FoodDonation
  - DrugDonation

## Backend
- [ ] create class / record "Project", with:
  - id
  - name
  - description
  - category
  - demands
  - progress
  - location

- [ ] create enum "Category", with:
  - Donation
  - Participation

- [ ] create enum "Demand", with:
  - MoneyDonation
  - DonationInKind
  - FoodDonation
  - DrugDonation

# Sprint Ready Checklist 
[ ] Acceptance criteria defined 
[ ] Team understands acceptance criteria 
[ ] Team has defined solution / steps to satisfy acceptance criteria 
[ ] Acceptance criteria is verifiable / testable
