### ISSUE TITLE
feature progress 

### ISSUE THREAD

**Issue by Ben-21** [Ben-21/capstone-neuefische#21]
# User story
As a ..., I want to ..., so I can ...

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [ ] users can click on a button which opens a new side (or modal) where they can put in their personal information and the amount they want to spend 

# Tasks
## Frontend
- [ ] instead of progress, users can specify a goal (number of participants or amount of money)
## Backend
- [ ] implement "goal" in model (used for both, participation and donation) as BigDecimal

# Sprint Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Team understands acceptance criteria 
- [ ] Team has defined solution / steps to satisfy acceptance criteria 
- [ ] Acceptance criteria is verifiable / testable
