### ISSUE TITLE
TBD - feature participants / user management

### ISSUE THREAD

**Issue by Ben-21** [Ben-21/capstone-neuefische#22]
TBD!!!

# User story
As a user, I want to be able participate in a project, so I can specify the amount of money I want to spend or that I am applying for a participation project.

# Acceptance criteria

- [ ] Users can click on a button to apply for a project, if it is category.participation
- [ ] Users can submit their personal data (address)
- [ ] users can specify the amount of money they want to spend, when it is category.donation or demand.moneydonation
- [ ] the input field for donation is only visible when it is category.donation or demand.moneydonation
- [ ] apply button is only visible when category.participation 

# Tasks
## Frontend
- [ ]
## Backend
- [ ] add a field to the model for donations
- [ ] add a field for volunteers
- [ ] make enum for participant
- [ ] add participants to the project

# Sprint Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Team understands acceptance criteria 
- [ ] Team has defined solution / steps to satisfy acceptance criteria 
- [ ] Acceptance criteria is verifiable / testable
