### ISSUE TITLE
model extension - goal, donation, volunteer

### ISSUE THREAD

**Issue by Ben-21** [Ben-21/capstone-neuefische#33]
# Tasks
## Frontend
- [ ] add donation, volunteer, goal to model
- [ ] rename model "ProjectCreation"

## Backend
- [ ] add donation, volunteer, goal to model
- [ ] initiate in service
- [ ] adjust tests
